create table if not exists public.screener_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_id text not null,
  as_of timestamptz,
  generated_at timestamptz not null,
  payload jsonb not null,
  received_at timestamptz not null default now()
);

create index if not exists screener_snapshots_generated_at_desc_idx
  on public.screener_snapshots (generated_at desc);

alter table public.screener_snapshots enable row level security;

revoke all on public.screener_snapshots from anon, authenticated;

create or replace function public.prevent_screener_snapshots_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'screener_snapshots is append-only';
end;
$$;

drop trigger if exists screener_snapshots_block_mutations
  on public.screener_snapshots;

create trigger screener_snapshots_block_mutations
  before update or delete on public.screener_snapshots
  for each row execute function public.prevent_screener_snapshots_mutation();
